language: node_js

cache: npm

node_js:
  - '8'

sudo: false

#before_install:
#  - yarn global add codeclimate-test-reporter

#before_deploy:
#  - npm run build
#  - cd dist

script:
  - npm run test

after_script:
#  - npm run build # make a dist folder
#  - codeclimate-test-reporter < coverage/lcov.info
#  - node_modules/.bin/coveralls < coverage/lcov.info

deploy:
  - provider: npm
    email: 'devmonk@mediamonks.com'
    api_key: $NPM_TOKEN
    on:
      tags: true
      node: '8'
    skip_cleanup: true
